/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Notification {
  'id' : string,
  'metadata' : [] | [string],
  'userId' : Principal,
  'notificationType' : NotificationType,
  'isRead' : boolean,
  'notifiedBy' : Principal,
  'timestamp' : Time,
}
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'message' : null } |
  { 'mention' : null } |
  { 'follow' : null };
export interface Post {
  'id' : string,
  'hasStory' : boolean,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'isPublic' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'websiteUrl' : string,
  'isPrivate' : boolean,
  'avatarUrl' : string,
  'gender' : [] | [Gender],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotification' : ActorMethod<[string, NotificationType], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, boolean], string>,
  'deletePost' : ActorMethod<[string], undefined>,
  'fetchNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublicStoriesForUser' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'publicStories' : ActorMethod<[], Array<Post>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];